In [1]:
print("Hello world")

Hello world


In [2]:
x: int = 5
y: int = 10

print(x ** y)

9765625


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
# print(arr * 2)
# print(arr + 10)

print(arr.mean())
print(arr.sum())

[1 2 3 4 5]
3.0
15


In [6]:
import numpy as np

arr = np.array([[2, 5], [3, 7]])

print(arr * 2)

[[ 4 10]
 [ 6 14]]


In [7]:
import numpy as np

my_arr = np.arange(10)

print(my_arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', ''],
    'Age': [25, 30, 35, 0],
    'Salary': [50000,  60000, 70000, 0]
}
df = pd.DataFrame(data)

print(df[['Name', 'Age']])

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3             0


In [28]:
import pandas as pd

data = {
    'Name': ['Omar', 'Ahmed', 'Ali', 'Osama', 'Marwan'],
    'Age': [28, 34, 25, 31, 21],
    'City': ['New York', 'Chicago', 'New York', 'Chicago', 'Boston'],
    'Purchase_Amount': [150, 200, 300, 90, 175],
    'Items_Bought': [1, 3, 4, 2, 6]
}

df = pd.DataFrame(data)

def get_city_df(city_name: str):
    return df[df['City'] == city_name]


def calc_city_average_price(city_name: str) -> float:
    df_city = get_city_df(city_name)
    return df_city['Average_Price'].values.sum()


print("All Customers from New York:")
print("============================")
print(get_city_df('New York'))

df['Average_Price'] = df['Purchase_Amount'] / df['Items_Bought']

calc_city_average_price('New York')

# Filter customers who spent 
# more than $100 AND bought more than 3 items

print("\nCustomers who spent > $100 AND bought > 3 items: 🫶")

vip_customers = df[ (df['Purchase_Amount'] > 100) & (df['Items_Bought'] > 3) ]

print(f"\n{vip_customers}")

# Sort the DataFrame by 
# Purchase_Amount (highest first)

print("\n", df.sort_values('Purchase_Amount', ascending=False) )

# Find the customer with
# the highest Average_Price

print("\nCustomer with the highest average price:\n")

print(df.sort_values('Average_Price', ascending=False).iloc[0])

All Customers from New York:
   Name  Age      City  Purchase_Amount  Items_Bought
0  Omar   28  New York              150             1
2   Ali   25  New York              300             4

Customers who spent > $100 AND bought > 3 items: 🫶

     Name  Age      City  Purchase_Amount  Items_Bought  Average_Price
2     Ali   25  New York              300             4      75.000000
4  Marwan   21    Boston              175             6      29.166667

      Name  Age      City  Purchase_Amount  Items_Bought  Average_Price
2     Ali   25  New York              300             4      75.000000
1   Ahmed   34   Chicago              200             3      66.666667
4  Marwan   21    Boston              175             6      29.166667
0    Omar   28  New York              150             1     150.000000
3   Osama   31   Chicago               90             2      45.000000

Customer with the highest average price:

Name                   Omar
Age                      28
City            

In [31]:
import pandas as pd
import numpy as np

data = {
    'Customer': ['John', 'Sarah', 'Mike', 'Emily', 'David', 'Anna', 'Tom'],
    'Age': [28, '34', 22, '29', '41', 35, None],
    'City': ['New York', 'Chicago', 'new york', 'CHICAGO', 'Boston', 'Chicago', 'New York'],
    'Purchase_Amount': [150, 200, None, 300, 120, 180, 250],
    'Items_Bought': [3, 5, 2, 7, 4, '3', 6],
    'Join_Date': ['2023-01-15', '2023/02/20', '15-03-2023', '2023-04-10', '2023-05-05', '2023-06-01', '2023-07-12']
}

df = pd.DataFrame(data)

df['Age'].astype(int)
df['Items_Bought'].astype(int)
pd.to_datetime( df['Join_Date'] )

df['City'].str.lower().str.capitalize()

df['Age'].fillna(df['Age'].mean())

print(df.head())

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'